<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# -->
<a href="insertbet.php"><img src="images/icons/new.png" alt="<!-- #NewBet --><!-- NewBet# -->" border="0"></a></p>
</h1>
<!-- #Bets -->
<div id="betlayer">
<img class="cat-image" src="<!-- #ImageSrc --><!-- ImageSrc# -->" alt="Bet Image" /> 

<p><!-- #BetNr --><!-- BetNr# --><!-- #CategoryName -->
<!-- CategoryName# --><span class="bettitle"><!-- #Title -->
<!-- Title# --></span> <!-- #AnnullateLink --><!-- AnnullateLink# --></p>

<p><span class="pretime"><!-- #From --><!-- From# -->
</span> <!-- #Start --><!-- Start# -->
<span class="pretime"><!-- #Until --><!-- Until# -->
</span> <!-- #End --><!-- End# --></p>

<p class="subtitle"><!-- #SubTitle --><!-- SubTitle# --></p>

<!-- #Possibilities -->
<p>
<!-- #PossibilityName --><!-- PossibilityName# -->
<!-- #PossibilityQuote --><!-- PossibilityQuote# -->
<!-- #FreezeArea -->
<a href="freezer.php?bet=<!-- #BetID --><!-- BetID# -->&pos=<!-- #PossibilityID --><!-- PossibilityID# -->">
<img src="images/icons/freeze.png" border="0"></a>
<!-- FreezeArea# -->
</p>
 <!-- Possibilities# -->


<p>&nbsp;</p>
</div>

<!-- Bets# -->
</div>
<!-- #NavArea -->
<div align="center">
<a href="betlist.php?pn=<!-- #FirstPage --><!-- FirstPage# -->">
<img src="images/icons/start.png" border="0">
</a>
<a href="betlist.php?pn=<!-- #PrevPage --><!-- PrevPage# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="betlist.php?pn=<!-- #NextPage --><!-- NextPage# -->">
<img src="images/icons/next.png" border="0">
</a>
<a href="betlist.php?pn=<!-- #LastPage --><!-- LastPage# -->">
<img src="images/icons/finish.png" border="0">
</a>
</div>
<!-- NavArea# -->
</div>

<div id="rightlayer" class="right-layer">
