<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>


<table summary="Category Table" width="90%" align="center">
	<tr>
		<td width="5%" class="noborder"><!-- #CategoryID --><!-- CategoryID# --></td>
		<td width="10%"  class="category-<!-- #CategoryID --><!-- CategoryID# -->">
			<img class="cat-image" src="<!-- #CategoryImageSrc --><!-- CategoryImageSrc# -->"
		    alt ="Category Image" />
		</td>
		<td>
			<p><!-- #CategoryName --><!-- CategoryName# --></p>
			<p><!-- #CategoryDescription --><!-- CategoryDescription# --></p>
		</td>
	</tr>
</table>
<p>
<!-- #Link -->
<a href="categoryedit.php?id=<!-- #CategoryID --><!-- CategoryID# -->&ac=<!-- #Action --><!-- Action# -->"><!-- #ActionName --><!-- ActionName# --></a> 
<!-- Link# -->
</p>
<p>
<a href="categorylist.php"><!-- #BackList --><!-- BackList# --></a>
</p>
</div>
</div>

<div id="rightlayer" class="right-layer">

