<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<form name="changebalanceform2" action="" method="post">
<p><!-- #ActualBalance --><!-- ActualBalance# -->
<!-- #ActualBalanceValue --><!-- ActualBalanceValue# --></p>
<p><!-- #NewBalance --><!-- NewBalance# --><input type="text" name="balance" size="5" value="<!-- #NewBalanceValue --><!-- NewBalanceValue# -->" readonly="readonly"></p>
<input type="submit" name="chbald" value="<!-- #Edit --><!-- Edit# -->">
<input type="submit" name="chbald" value="<!-- #Delete --><!-- Delete# -->">
</form>

</div>
</div>

<div id="rightlayer" class="right-layer">

