<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<table summary="Category Table" width="90%" align="center">
	<tr>
		<td width="10%">
			<img class="cat-image" src="<!-- #CategoryImageSrc --><!-- CategoryImageSrc# -->"
		    alt ="Category Image" />
		</td>
		<td>
			<p><!-- #CategoryName --><!-- CategoryName# --></p>
			<p><!-- #CategoryDescription --><!-- CategoryDescription# --></p>
		</td>
	</tr>
</table><p>

<a href="categorylist.php"><!-- #BackList --><!-- BackList# --></a>
</div>
</div>

<div id="rightlayer" class="right-layer">
