<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<form name="catform" action="" method="post" enctype="multipart/form-data">

<h3><!-- #Message2 --><!-- Message2# --></h3>

<p><!-- #CategoryName --><!-- CategoryName# --></p>
<p><input type="text" name="newcategoryname" class="textfield"   value="<!-- #InsCategoryName --><!-- InsCategoryName# -->"></p>
<p><!-- #CategoryDesc --><!-- CategoryDesc# --></p>
<p><input type="text" name="newcategorydesc" class="textfield" value="<!-- #InsCategoryDesc --><!-- InsCategoryDesc# -->"></p>
<p><!-- #CategoryImage --><!-- CategoryImage# --></p>
<p><input type="file" name="newcategoryimage" value="<!-- #InsCategoryImage --><!-- InsCategoryImage# -->"></p>

<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->"  class="button"value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
<input type="submit" name="<!-- #ButtonGoName --><!-- ButtonGoName# -->" class="button" value="<!-- #ButtonGoValue --><!-- ButtonGoValue# -->">
</form>

</div>
</div>

<div id="rightlayer" class="right-layer">
