<div id="menu" class="menu">
<p class="menutitle">
Menu: 
</p>
<p>
<!-- #AddSite -->
<a href="addsite.php">
<img src="/images/icons/new16.png">
</a><br />
<!-- AddSite# -->

<!-- #Item -->

<!-- #DeleteSite -->
<a href="deletesite.php?sid=<!-- #Id2 --><!-- Id2# -->">
<img src="/images/icons/delete16.png">
</a>
<!-- DeleteSite# -->

<!-- #EditSite -->
<a href="addsite.php?sid=<!-- #Id2 --><!-- Id2# -->">
<img src="/images/icons/edit16.png">
</a>
<!-- EditSite# -->

<a href="showsite.php?sid=<!-- #Id --><!-- Id# -->.html">
<!-- #Name --><!-- Name# --></a>
<br />
<!-- Item# -->

<!-- #FixItem -->
<a href="<!-- #Link --><!-- Link# -->">
<!-- #Name --><!-- Name# --></a>
<br />
<!-- FixItem# -->

</p>
<p class="footer"><a href="http://betster.sourceforge.net">BetSter v <!-- #Version --><!-- Version# --></a></p>

</div>
</div>
