<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>

<table summary="Table about my bets" class="listtable">
<tr>
<th><!-- #BetTitle --><!-- BetTitle# --></th>
<th><!-- #PosTitle --><!-- PosTitle# --></th>
<th><!-- #CreditsTitle --><!-- CreditsTitle# --></th>
<th><!-- #TimeTitle --><!-- TimeTitle# --></th>
</tr>

<!-- #Transactions -->
<tr
class="<!-- #TransactionsCSS --><!-- TransactionsCSS# -->">
<td><!-- #BetName --><!-- BetName# --></td>
<td><!-- #PossibilityName --><!-- PossibilityName# --></td>
<td><!-- #Credits --><!-- Credits# --></td>
<td><!-- #Time --><!-- Time# --></td>
</tr>

<!-- Transactions# -->
</table>
<!-- #NavArea -->
<a href="mybets.php?<!-- #PrevPage --><!-- PrevPage# --><!-- #UserId --><!-- UserId# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="mybets.php?<!-- #NextPage --><!-- NextPage# --><!-- #UserId --><!-- UserId# -->">
<img src="images/icons/next.png" border="0">
</a>
<!-- NavArea# -->
</div>
</div>
<div id="rightlayer" class="right-layer">

