<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<table summary="Profile Table">
    <tr>
        <td class="noborder"><!-- #UsernameTitle --><!-- UsernameTitle# --></td>
        <td class="noborder"><!-- #Username --><!-- Username# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #FirstnameTitle --><!-- FirstnameTitle# --></td>
        <td class="noborder"><!-- #Firstname --><!-- Firstname# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #LastnameTitle --><!-- LastnameTitle# --></td>
        <td class="noborder"><!-- #Lastname --><!-- Lastname# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #EmailTitle --><!-- EmailTitle# --></td>
        <td class="noborder"><!-- #Email --><!-- Email# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #BalanceTitle --><!-- BalanceTitle# --></td>
        <td class="noborder"><!-- #Balance --><!-- Balance# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #StatusTitle --><!-- StatusTitle# --></td>
        <td class="noborder"><!-- #Status --><!-- Status# --></td>
    </tr>
</table>
</div>
</div>
<div id="rightlayer" class="right-layer">



