<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<table summary="Profile Table">
    <tr>
        <td>Id</td>
        <td><!-- #Id --><!-- Id# --></td>
    </tr>
    <tr>
        <td><!-- #UsernameTitle --><!-- UsernameTitle# --></td>
        <td><!-- #XUsername --><!-- XUsername# --></td>
    </tr>
    <tr>
        <td><!-- #FirstnameTitle --><!-- FirstnameTitle# --></td>
        <td><!-- #Firstname --><!-- Firstname# --></td>
    </tr>
    <tr>
        <td><!-- #LastnameTitle --><!-- LastnameTitle# --></td>
        <td><!-- #Lastname --><!-- Lastname# --></td>
    </tr>
    <tr>
        <td><!-- #EmailTitle --><!-- EmailTitle# --></td>
        <td><!-- #Email --><!-- Email# --></td>
    </tr>
    <tr>
        <td><!-- #BalanceTitle --><!-- BalanceTitle# --></td>
        <td><!-- #XBalance --><!-- XBalance# --></td>
    </tr>
    <tr>
        <td><!-- #StatusTitle --><!-- StatusTitle# --></td>
        <td><!-- #Status --><!-- Status# --></td>
    </tr>
</table>
<p>
<!-- #Link -->
<a href="editprofile.php?ac=<!-- #Action --><!-- Action# -->&id=<!-- #Id --><!-- Id# -->"><!-- #ActionName --><!-- ActionName# --></a>   
<!-- Link# -->
</p>
<p>
<a href="showprofile.php?id=<!-- #Prev --><!-- Prev# -->">
<img src="images/icons/previous.png" alt="<!-- #PrevName --><!-- PrevName# -->" border="0"></a> 
<!-- #Actual --><!-- Actual# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="showprofile.php?id=<!-- #Next --><!-- Next# -->">
<img src="images/icons/next.png" alt="<!-- #NextName --><!-- NextName# -->" border="0"></a>
</p>
<p>
<!-- #BackLink1 --><!-- BackLink1# -->
</p>
<p>
<!-- #BackLink2 --><!-- BackLink2# -->
</p>
</div>
</div>

<div id="rightlayer" class="right-layer">