<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>

<table summary="User Table" class="listtable">
<!-- #UserHead -->
<tr>
<th><!-- #StatusName --><!-- StatusName# --></th>
<th>Id</td>
<th><!-- #UsernameName --><!-- UsernameName# --></th>
<th><!-- #BalanceName --><!-- BalanceName# --></th>
</tr>
<!-- UserHead# -->

<!-- #User -->
<tr>
<td><!-- #Status --><!-- Status# --></td>
<td><!-- #Id --><!-- Id# --></td>
<td><a href="showprofile.php?id=<!-- #Id --><!-- Id# -->"><!-- #Username --><!-- Username# --></a></td>
<td><!-- #Balance --><!-- Balance# --></td>
</tr>
<!-- User# -->
</table>

<!-- #NavArea -->
<a href="userlist.php?<!-- #PrevPage --><!-- PrevPage# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="userlist.php?<!-- #NextPage --><!-- NextPage# -->">
<img src="images/icons/next.png" border="0">
</a>
<!-- NavArea# -->

<p>
<!-- #BackLink1 --><!-- BackLink1# -->
</p>
</div>
</div>

<div id="rightlayer" class="right-layer">
