<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>

<!-- #Bets -->

<div id="betlayer"
class="<!-- #CategoryCSS --><!-- CategoryCSS# -->"><img
class="cat-image"
src="<!-- #ImageSrc --><!-- ImageSrc# -->"
alt="Category Image" /> 


<p><!-- #BetNr --><!-- BetNr# --><!-- #CategoryName -->
<!-- CategoryName# --><span class="bettitle"><!-- #Title -->
<!-- Title# --></span></p>

<p><span class="pretime">Start:</span> <!-- #Start --><!-- Start# -->
<span class="pretime">End:</span> <!-- #End --><!-- End# --></p>

<p class="subtitle"><!-- #SubTitle --><!-- SubTitle# --></p>

<p>
<!-- #Possibilities -->
<!-- #PossibilityName --><!-- PossibilityName# -->
<!-- #PossibilityQuote --><!-- PossibilityQuote# -->
<!-- Possibilities# -->

</p>

</div>
<p style="clear:left"></p>
<!-- Bets# -->

</div>

<!-- #NavArea -->
<a href="archive.php?pn=<!-- #PrevPage --><!-- PrevPage# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="archive.php?pn=<!-- #NextPage --><!-- NextPage# -->">
<img src="images/icons/next.png" border="0">
</a>
<!-- NavArea# -->
</div>
<div class="right-layer">