<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# -->
<a href="insertcategory.php"><img src="images/icons/new.png" alt="<!-- #NewCat --><!-- NewCat# -->" border="0"></a>
</h1>


<!-- #Categories -->
<table summary="Category Table" width="90%" align="center">
<tr>
<td class="category">
<img class="cat-image" src="<!-- #CategoryImageSrc --><!-- CategoryImageSrc# -->"
alt ="Category Image" />
</td>
<td width="75%" class="category">
<p><!-- #CategoryName --><!-- CategoryName# --></p>
<p><!-- #CategoryDescription --><!-- CategoryDescription# --></p>
</td>
<td class="noborder">
</td>
<td valign="middle" class="noborder">
<a href="categoryedit.php?id=<!-- #CategoryID --><!-- CategoryID# -->">
<img src="images/icons/edit.png" border="0">
</a>

<!-- #CategoryUpImage -->
<a href="categorylist.php?id=<!-- #CategoryID --><!-- CategoryID# -->&dir=up">
<img src="images/icons/up.png" border="0">
</a>
<!-- CategoryUpImage# -->

</td>

<td valign="middle" class="noborder">
<a href="categorydel.php?id=<!-- #CategoryID --><!-- CategoryID# -->">
<img src="images/icons/anullate.png" border="0">
</a>

<!-- #CategoryDownImage -->
<a href="categorylist.php?id=<!-- #CategoryID --><!-- CategoryID# -->&dir=down">
<img src="images/icons/down.png" border="0">
</a>
<!-- CategoryDownImage# -->

</td>

</tr>
</table>

<!-- Categories# -->

<!-- #NavArea -->
<div align="center">
<a href="categorylist.php?<!-- #FirstPage --><!-- FirstPage# -->">
<img src="images/icons/start.png" border="0">
</a>
<a href="categorylist.php?<!-- #PrevPage --><!-- PrevPage# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #NumPages --><!-- NumPages# -->
<a href="categorylist.php?<!-- #NextPage --><!-- NextPage# -->">
<img src="images/icons/next.png" border="0">
</a>
<a href="categorylist.php?<!-- #LastPage --><!-- LastPage# -->">
<img src="images/icons/finish.png" border="0">
</a>
</div>
<!-- NavArea# -->
<p>
<!-- #BackLink1 --><!-- BackLink1# -->
</p>

</div>
</div>

<div id="rightlayer" class="right-layer">
