<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<form name="categoryeditform" action="" method="post" enctype="multipart/form-data">

<p><!-- #NewCategoryName --><!-- NewCategoryName# --></p>
<p><input type="text" name="newcategoryname"  value="<!-- #InsNewCategoryName --><!-- InsNewCategoryName# -->"></p>
<p><!-- #NewCategoryDesc --><!-- NewCategoryDesc# --></p>
<p><input type="text" name="newcategorydesc" value="<!-- #InsNewCategoryDesc --><!-- InsNewCategoryDesc# -->"></p>
<p><!-- #NewCategoryImage --><!-- NewCategoryImage# --></p>
<p><input type="file" name="newcategoryimage" value="<!-- #InsNewCategoryImage --><!-- InsNewCategoryImage# -->"></p>

<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->"value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
<input type="submit" name="edit
" value="<!-- #ButtonGoValue --><!-- ButtonGoValue# -->">


</form>
<p>
<a href="categorylist.php"><!-- #BackList --><!-- BackList# --></a>
</p>
</div>
</div>

<div id="rightlayer" class="right-layer">

