<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<p><!-- #Message1 --><!-- Message1# --></p>

<form name="accountform" action="" method="post">

<p><!-- #Email --><!-- Email# --><br />
<input type="text" name="email" class="textfield"></p>

<input type="submit" value="Send" class="button">
<input type="reset" value="Clear" class="button">
</form>

</div>
</div>
<div class="right-layer">

