<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<p><!-- #Message1 --><!-- Message1# --></p>

<form name="accountform" action="" method="post">
<p><!-- #Username --><!-- Username# --><br />
<input type="text" name="ausername" class="textfield"></p>
<p><!-- #Email --><!-- Email# --><br />
<input type="text" name="email" class="textfield"></p>
<p><!-- #Firstname --><!-- Firstname# --><br />
<input type="text" name="firstname" class="textfield"></p>
<p><!-- #Lastname --><!-- Lastname# --><br />
<input type="text" name="lastname" class="textfield"></p>
<p><!-- #Password1 --><!-- Password1# --><br />
<input type="password" name="password1" class="textfield"></p>
<p><!-- #Password2 --><!-- Password2# --><br />
<input type="password" name="password2" class="textfield"></p>
<input type="submit" value="Send" class="button">
<input type="reset" value="Clear" class="button">
</form>

</div>
</div>
<div class="right-layer">

