<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<div class="betlayer">
<!-- #Text --><!-- Text# -->

<label><!-- #Date --><!-- Date# --></label>
</div>
<form action="" method="post" name="checker">
<input name="delete" value="<!-- #ButtonDelete --><!-- ButtonDelete# -->" type="submit">
<input name="cancel" value="<!-- #ButtonCancel --><!-- ButtonCancel# -->" type="submit">
</form>
</div>
</div>
<div class="right-layer">