<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<p>
<!-- #AdminMenu -->
<a href="editprofile.php?acd=<!-- #Ac0 --><!-- Ac0# -->&id=<!-- #Id --><!-- Id# -->"><!-- #Yes --><!-- Yes# --></a>|
<a href="showprofile.php?id=<!-- #Id --><!-- Id# -->"><!-- #No --><!-- No# --></a>
<!-- AdminMenu# -->
<p>
<a href="userlist.php"><!-- #Back --><!-- Back# --></a>
</p>

</div>
</div>

<div id="rightlayer" class="right-layer">

