<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<p><!-- #Message1 --><!-- Message1# --></p>

<form name="forgotpwdform" action="" method="post">
<p><!-- #Username --><!-- Username# --><br />
<input type="text" name="ausername" class="textfield"></p>
<p><!-- #Email --><!-- Email# --><br />
<input type="text" name="email" class="textfield"></p>
<p><!-- #Firstname --><!-- Firstname# --><br />

<input type="submit" value="Send" class="button">
<input type="reset" value="Clear" class="button">
</form>

</div>
</div>
<div class="right-layer">

