<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<div id="betlayer"
class="category-<!-- #CategoryCSS --><!-- CategoryCSS# -->"><img
class="cat-image"
src="<!-- #ImageSrc --><!-- ImageSrc# -->"
alt="Category Image" /> 

<p><!-- #CategoryName --><!-- CategoryName# -->
<span class="bettitle"><!-- #Title -->
<!-- Title# --></span></p>

<p><span class="pretime">Von:</span> <!-- #Start --><!-- Start# -->
<span class="pretime">bis:</span> <!-- #End --><!-- End# --></p>

<p class="subtitle"><!-- #SubTitle --><!-- SubTitle# --></p>

<!-- #Possibilities -->
<p>
<!-- #PossibilityName --><!-- PossibilityName# -->
</p>
<!-- Possibilities# -->
<p><a href="index.php"><!-- #BackHome --><!-- BackHome# --></a></p>
<p>&nbsp;</p>
</div>

<form name="accountform" action="" method="post">
<input type="submit" name="<!-- #ButtonGoName --><!-- ButtonGoName# -->" value="<!-- #ButtonGoValue --><!-- ButtonGoValue# -->">
<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->"value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
</form>


</div>
</div>

<div id="rightlayer" class="right-layer">
