<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="generator" content="HTML Tidy, see www.w3.org" />
<title>BetSter - The OpenSource betoffice</title>
<meta http-equiv="Content-Type"
content="text/html; charset=iso-8859-1" />
<meta name="dc.title"       content="" />
<meta name="author"         content="" />
<meta name="dc.creator"     content="" />
<meta name="dc.subject"     content="" />
<meta name="keywords"       content="Betoffice, Gambling, Betting" />
<meta name="dc.description" content="Betster is an open-source betoffice for online betting" />
<meta name="description"    content="BetSter - The OpenSource betoffice" />
<meta name="dc.type"        content="betoffice" />
<meta name="resource-type"  content="document" />
<meta name="dc.format"      scheme="IMT" content="text/html" />
<meta name="dc.coverage"    content="global" />
<meta name="distribution"   content="GLOBAL" /> 
<meta name="dc.rights"      content="" />
<meta name="copyright"      content="GPL" />
<meta name="robots" content="ALL,INDEX,FOLLOW" />
<meta name="revisit-after" content="7 days" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<link href="/css/calendar-brown.css" rel="stylesheet" type="text/css" />
</head>
<body>
