<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>

<table summary="Highscore Table" class="listtable">
<tr>
<th><!-- #PlaceName --><!-- PlaceName# --></th>
<th><!-- #UsernameName --><!-- UsernameName# --></th>
<th><!-- #BalanceName --><!-- BalanceName# --></th>
</tr>

<!-- #User -->
<tr>
<td><!-- #Place --><!-- Place# --></td>
<td><!-- #Username --><!-- Username# --></td>
<td><!-- #Balance --><!-- Balance# --></td>
</tr>
<!-- User# -->
</table>
</div>
</div>

<div id="rightlayer" class="right-layer">
