<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>

<!-- #Bets -->
<div id="betlayer"
class="<!-- #CategoryCSS --><!-- CategoryCSS# -->">
<img
class="cat-image"
src="<!-- #ImageSrc --><!-- ImageSrc# -->" 
alt ="Category Image" /> 
<form name="betform" action="betchecker.php" method="post">

<p>
<!-- #CategoryName --><!-- CategoryName# -->
<span class="bettitle"><!-- #Title --><!-- Title# --></span>
<br><span class="pretime"><!-- #Until -->
<!-- Until# --></span><!-- #End --><!-- End# --><br>
<span class="subtitle"><!-- #SubTitle --><!-- SubTitle# --></span>
</p>


<!-- #Possibilities -->
<nobr>
<input type="radio" name="pos" class="betoption"
value="<!-- #BetID --><!-- BetID# --><!-- #PossibilityID --><!-- PossibilityID# -->" />
<!-- #PossibilityName --><!-- PossibilityName# -->
<!-- #PossibilityQuote --><!-- PossibilityQuote# -->
</nobr>
&nbsp;
<!-- Possibilities# -->


<p>Credits: <input type="text" class="betfield" name="credits" size="5" />
<input
type="submit" name="Betbutton" class="betbutton" value="Bet" /></p>
</form>

</div>
<p style="clear:left"></p>
<!-- Bets# -->

<!-- #NavArea -->
<a href="index.html?pn=<!-- #PrevPage --><!-- PrevPage# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="index.html?pn=<!-- #NextPage --><!-- NextPage# -->">
<img src="images/icons/next.png" border="0">
</a>
<!-- NavArea# -->
</div>
</div>
<div class="right-layer">
