<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<form name="deleteform" action="" method="post">
<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->"  class="button" value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
<input type="submit" name="<!-- #ButtonContinueName --><!-- ButtonContinueName# -->"  class="button" value="<!-- #ButtonContinueValue --><!-- ButtonContinueValue# -->">
</form>
</div>
</div>

<div id="rightlayer" class="right-layer">