<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<form name="accountform" action="" method="post" enctype="multipart/form-data">
<h2><!-- #PosTitle --><!-- PosTitle# --></h2>

<!-- #Possibilities -->
<p><!-- #Pos --><!-- Pos# --></p>
	<p><input type="text" name="<!-- #PosName --><!-- PosName# -->" class="textfield" value="<!-- #PosValue --><!-- PosValue# -->"></p>
<!-- Possibilities# -->

<!-- #HiddenFields --><!-- HiddenFields# -->

<input type="submit" name="<!-- #ButtonBackName --><!-- ButtonBackName# -->"class="button"  value="<!-- #ButtonBackValue --><!-- ButtonBackValue# -->">
<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->" class="button" value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
<input type="submit" name="<!-- #ButtonGoName --><!-- ButtonGoName# -->" class="button" value="<!-- #ButtonGoValue --><!-- ButtonGoValue# -->">
</form>

</div>
</div>

<div id="rightlayer" class="right-layer">