<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<form name="accountform" action="" method="post">


<div id="betlayer">
<img
class="cat-image"
src="<!-- #ImageSrc --><!-- ImageSrc# -->"
alt="Category Image" /> 

<p><!-- #CategoryName --><!-- CategoryName# -->
<span class="bettitle"><!-- #Title -->
<!-- Title# --></span></p>

<p><span class="pretime">Von:</span> <!-- #Start --><!-- Start# -->
<span class="pretime">bis:</span> <!-- #End --><!-- End# --></p>

<p class="subtitle"><!-- #SubTitle --><!-- SubTitle# --></p>

<!-- #Possibilities -->
<span class="nowrap">
<!-- #PossibilityName --><!-- PossibilityName# -->
</span>
<!-- Possibilities# -->
<!-- #HiddenFields --><!-- HiddenFields# -->
<p>&nbsp;</p>
</div>

<input type="submit" name="<!-- #ButtonBackName --><!-- ButtonBackName# -->" class="button" value="<!-- #ButtonBackValue --><!-- ButtonBackValue# -->">
<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->" class="button" value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
<input type="submit" name="<!-- #ButtonGoName --><!-- ButtonGoName# -->"  class="button" value="<!-- #ButtonGoValue --><!-- ButtonGoValue# -->">
</form>

</div>
</div>

<div id="rightlayer" class="right-layer">

