<div id="contentlayer" class="content-layer">

<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<form name="accountform" action="" method="post" enctype="multipart/form-data">

<!-- #Categories -->
<table summary="Category Table" width="90%" align="center">
<tr>
<td class="noborder">
<input type="radio" name="category"
value="<!-- #CategoryID --><!-- CategoryID# -->" /></td>
<td class="category">
<img class="cat-image" src="<!-- #CategoryImageSrc --><!-- CategoryImageSrc# -->" alt ="Category Image" />
</td>
<td width="75%" class="category">
<p><!-- #CategoryName --><!-- CategoryName# --></p>
<p><!-- #CategoryDescription --><!-- CategoryDescription# --></p>
</td>
<td class="noborder">
</td>
<td valign="middle" class="noborder">
</td>
<td valign="middle" class="noborder">
</td>
</tr>
</table>
<!-- Categories# -->

<!-- #HiddenFields --><!-- HiddenFields# -->

<input type="submit" name="<!-- #ButtonBackName --><!-- ButtonBackName# -->" class="button" value="<!-- #ButtonBackValue --><!-- ButtonBackValue# -->">
<input type="submit" name="<!-- #ButtonDeleteName --><!-- ButtonDeleteName# -->"  class="button"value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
<input type="submit" name="<!-- #ButtonGoName --><!-- ButtonGoName# -->" class="button" value="<!-- #ButtonGoValue --><!-- ButtonGoValue# -->">
</form>

</div>
</div>

<div id="rightlayer" class="right-layer">
