<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>

<table summary="Log Table" class="listtable">

<!-- #UserHead -->
<tr>
<th>Id</th>
<th>Remote Address</th>
<th>Username</th>
<th>Event</th>
<th>Remote Agent</th>
<th>Date/Time</th>
</tr>
<!-- UserHead# -->

<!-- #Logs -->
<tr>
<td><!-- #Id--><!-- Id# --></td>
<td><!-- #RemoteAddress --><!-- RemoteAddress# --></td>
<td><!-- #Username --><!-- Username# --></td>
<td><!-- #Event--><!-- Event# --></td>
<td><!-- #RemoteAgent--><!-- RemoteAgent# --></td>
<td><!-- #DateTime--><!-- DateTime# --></td>
</tr>
<!-- Logs# -->
</table>

<!-- #NavArea -->
<a href="logs.php?<!-- #PrevPage --><!-- PrevPage# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="logs.php?<!-- #NextPage --><!-- NextPage# -->">
<img src="images/icons/next.png" border="0">
</a>
<!-- NavArea# -->

<p>
<!-- #BackLink1 --><!-- BackLink1# -->
</p>
</div>
</div>

<div id="rightlayer" class="right-layer">
