<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>
<form name="profile_edit" action="" method="POST">
<table summary="Profile Table">
    <tr>
        <td class="noborder"><!-- #UsernameTitle --><!-- UsernameTitle# --></td>
        <td class="noborder"><!-- #Username --><!-- Username# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #FirstnameTitle --><!-- FirstnameTitle# --></td>
        <td class="noborder"><input type="text" name="firstname" class="textfield" value="<!-- #Firstname --><!-- Firstname# -->"></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #LastnameTitle --><!-- LastnameTitle# --></td>
        <td class="noborder"><input type="text" name="lastname" class="textfield" value="<!-- #Lastname --><!-- Lastname# -->"></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #EmailTitle --><!-- EmailTitle# --></td>
        <td class="noborder"><!-- #Email --><!-- Email# -->  <a href="change_email.php">  <!-- #ChangeEmail --><!-- ChangeEmail# --></a></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #BalanceTitle --><!-- BalanceTitle# --></td>
        <td class="noborder"><!-- #Balance --><!-- Balance# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #StatusTitle --><!-- StatusTitle# --></td>
        <td class="noborder"><!-- #Status --><!-- Status# --></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #ChangePwd --><!-- ChangePwd# --></td>
        <td class="noborder"></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #OldPwd --><!-- OldPwd# --></td>
        <td class="noborder"><input type="password" name="pwd_old" class="textfield" ></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #NewPwd --><!-- NewPwd# --></td>
        <td class="noborder"><input type="password" name="pwd1" class="textfield" ></td>
    </tr>
    <tr>
        <td class="noborder"><!-- #NewPwdRep --><!-- NewPwdRep# --></td>
        <td class="noborder"><input type="password" name="pwd2" class="textfield" ></td>
    </tr>
</table>
<p>
<input type="submit" name="<!-- #ButtonInsertName --><!-- ButtonInsertName# -->" class="button" value="<!-- #ButtonInsertValue --><!-- ButtonInsertValue# -->">
<input type="reset" class="button" value="<!-- #ButtonDeleteValue --><!-- ButtonDeleteValue# -->">
</p>
</form>
</div>
</div>

<div id="rightlayer" class="right-layer">

