<div id="contentlayer" class="content-layer">
<h1><!-- #MainTitle --><!-- MainTitle# --></h1>
<h2><!-- #Message1 --><!-- Message1# --></h2>

<table summary="Table for all Tranasactions">
<!-- #TransactionsHead -->
<tr>
<th><!-- #UsernameName --><!-- UsernameName# --></th>
<th><!-- #BetName --><!-- BetName# --></th>
<th><!-- #PosName --><!-- PosName# --></th>
<th><!-- #CreditsName --><!-- CreditsName# --></th>
<th><!-- #DateTime --><!-- DateTime# --></th>
</tr>
<!-- TransactionsHead# -->

<!-- #Transactions -->
<tr class="<!-- #TransactionsCSS --><!-- TransactionsCSS# -->">
<td><a href="showprofile.php?id=<!-- #XUserId --><!-- XUserId# -->"><!-- #XUser --><!-- XUser# --></a></td>
<td><!-- #BetTitle --><!-- BetTitle# --></td>
<td><!-- #PossibilityName --><!-- PossibilityName# --></td>
<td><!-- #Credits --><!-- Credits# --></td>
<td><!-- #Time --><!-- Time# --></td>
</tr>
<!-- Transactions# -->
</table>

<!-- #NavArea -->
<a href="transactionlist.php?<!-- #PrevPage --><!-- PrevPage# --><!-- #UserId --><!-- UserId# -->">
<img src="images/icons/previous.png" border="0">
</a>
<!-- #ActualPage --><!-- ActualPage# --> / 
<!-- #LastPage --><!-- LastPage# -->
<a href="transactionlist.php?<!-- #NextPage --><!-- NextPage# --><!-- #UserId --><!-- UserId# -->">
<img src="images/icons/next.png" border="0">
</a>
<!-- NavArea# -->
<p>
<!-- #BackLink1 --><!-- BackLink1# -->
</p>
<p>
<!-- #BackLink2 --><!-- BackLink2# -->
</p>
</div>
</div>

<div id="rightlayer" class="right-layer">

