<div class="user-layer">
<!-- #LoginArea -->
<p class="menutitle">Login:</p>
<form name="loginform" action="" method="post">
<input type="text" value="username" class="login" name="username"  onFocus="javascript:this.value='';" /> <br />
<input type="password" value="password" class="login" name="password"  onFocus="javascript:this.value='';" /> <br />
<input type="submit" name="login" value="LOGIN" class="button" />
</form>
<p class="shortnews"><!-- #ShortNews --><!-- ShortNews# --></p>
<p><a href="create_account.php"><!-- #NewAccount --><!-- NewAccount# --></a><br />
<a href="forgot_pwd.php"><!-- #ForgotPwd --><!-- ForgotPwd# --></p>
<!-- LoginArea# -->

<!-- #UserArea -->
<p class="white"><!-- #Greet --><!-- Greet# --> <!-- #Username --><!-- Username# --></p>

<p class="shortnews"><!-- #ShortNews --><!-- ShortNews# --></p>

<p class="white"><!-- #YourBalance --><!-- YourBalance# --> <!-- #Balance --><!-- Balance# --></p>

<p><a href="mybets.php"><!-- #YourBets --><!-- YourBets# --></a><br />
<a href="mywins.php"><!-- #YourWins --><!-- YourWins# --></a><br />
<a href="profile.php"><!-- #YourProfile --><!-- YourProfile# --></a><br />
<a href="profile_edit.php"><!-- #EditProfile --><!-- EditProfile# --></a><br />
</p>
<br />
<br />
<a href="logout.php">LOGOUT</a></p>
<!-- UserArea# -->
</div>
